#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,starship,sway,waybar"
fi

if [[ -z $DOTFILESDIR ]]; then
    DOTFILESDIR=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILESDIR $DOTFILESDIR/install

